---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: bionic
    image: paulfantom/ubuntu-molecule:18.04
    privileged: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: xenial
    image: paulfantom/ubuntu-molecule:16.04
    privileged: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: stretch
    image: paulfantom/debian-molecule:9
    privileged: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: buster
    image: paulfantom/debian-molecule:10
    privileged: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos7
    image: paulfantom/centos-molecule:7
    privileged: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora
    image: paulfantom/fedora-molecule:30
    privileged: true
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: playbook.yml
    destroy: destroy.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
