---
- name: Prepare
  hosts: all
  tasks:
  - name: Gather variables for each operating system
    debug:
      var: ansible_distribution
  - name: Install mysqld server
    package:
      name: "{{ mysql_package }}"
      state: present
  - name: Start mysql server
    systemd:
      name: "{{ mysql_service }}"
      enabled: true
      state: started
  vars:
    mysql_service_map:
      CentOS: "mariadb"
      Debian: "mysqld"
      Fedora: "mariadb"
      Ubuntu: "mysql"
    mysql_package: "mariadb-server"
    mysql_service: "{{ mysql_service_map[ansible_distribution] | default('mysql') }}"
