---
- name: Prepare
  hosts: all
  tasks:
  - name: Install mysqld server
    package:
      name: "{{ mysql_package }}"
      state: present
  - name: Start mysql server
    systemd:
      name: "{{ mysql_service }}"
      state: started
  vars:
    mysql_package: "{{ 'mariadb' if (ansible_os_family | lower) == 'redhat' else 'mariadb-server' }}"
    mysql_service: mysqld

